- id: '1585261841669'
  alias: duna waterlevel notify
  description: Duna vízállás riasztás
  trigger:
  - below: '138'
    entity_id: sensor.god_duna_vizallas
    platform: numeric_state
  condition:
  - condition: template
    value_template: '{{ (as_timestamp(now()) - as_timestamp(states.automation.duna_waterlevel_notify.last_triggered  |
      default(0)) | int > 86400)}}'
  action:
  - data:
      message: A homokszigetre át lehet menni!
    service: notify.mobile_app_mi_9_se
- id: '1585672692839'
  alias: notification on tv
  description: ''
  trigger:
  - at: '18:00'
    platform: time
  condition: []
  action:
  - data:
      message: Boldi, moss fogat, kérlek!
    service: notify.nappali_tv
  mode: single
- id: '1585827520468'
  alias: Szürke víz kikapcs
  description: ''
  trigger:
  - entity_id: switch.gray_water
    for: 00:35:00
    from: 'off'
    platform: state
    to: 'on'
    enabled: true
  - platform: state
    entity_id:
    - switch.gray_water
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 35
      seconds: 0
    attribute: state
  condition: []
  action:
  - data: {}
    service: switch.turn_off
    target:
      entity_id: switch.gray_water
  - device_id: b054553f3d464229b377f92abc7941ad
    domain: mobile_app
    type: notify
    message: Valami lekapcsolt
    title: HAssio
    enabled: false
  - service: notify.mobile_app_mi_9_se
    data:
      message: Valami kikapcsolt
  mode: single
- alias: UPS changed state
  trigger:
  - platform: event
    event_type: nut.ups_event
  action:
  - service: notify.mobile_app_mi_9_se
    data_template:
      title: UPS changed state
      message: '{{ trigger.event.data.notify_msg }}'
      data:
        push:
          sound:
            name: default
            critical: 1
            volume: 1.0
  id: 8c8837088f3c4eeaa9c914db5d5d1102
- id: '1627032686499'
  alias: duna waterlevel notify szodi patak
  description: Duna vízállás Sződ-Rákosi patak
  trigger:
  - entity_id: sensor.god_duna_vizallas
    platform: numeric_state
    below: '460'
    above: 280
    enabled: true
  condition:
  - condition: template
    value_template: '{{ now() - state_attr(''automation.duna_waterlevel_notify_szodi_patak'',
      ''last_triggered'') > timedelta(hours=12) }}'
    enabled: true
  action:
  - data:
      message: A Sződi patakra fel lehet menni!
    service: notify.mobile_app_mi_9_se
  mode: single
- id: '1630009559453'
  alias: camera1_motion_detection
  description: ''
  trigger:
  - platform: state
    entity_id: switch.camera1_motion_detection
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: notify.mobile_app_mi_9_se
    data:
      message: mozgás
  mode: single
- id: '1641502924659'
  alias: Szürke víz
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: '1'
    enabled: false
  - platform: sun
    event: sunset
    offset: '60'
  condition:
  - condition: numeric_state
    entity_id: weather.otthon
    attribute: temperature
    above: '4'
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.gray_water
  - service: notify.mobile_app_mi_9_se
    data:
      message: Valami bekapcsolt
  mode: single
- id: '1672941820781'
  alias: Run Vacuum Zone
  description: ''
  trigger: []
  condition: []
  action:
  - service: vacuum.stop
    target:
      entity_id: vacuum.roborock_vacuum_a15
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - service: script.turn_on
    data_template:
      entity_id: ' {% if states.input_select.vacuum_rooms.state == "Zuhany" %} script.vacuum_shower
        {% elif states.input_select.vacuum_rooms.state == "Háló" %} script.vacuum_masterbed
        {% elif states.input_select.vacuum_rooms.state == "Előszoba" %} script.vacuum_lobby
        {% elif states.input_select.vacuum_rooms.state == "Boldi" %} script.vacuum_boldi
        {% elif states.input_select.vacuum_rooms.state == "Átjáró" %} script.vacuum_gateway
        {% elif states.input_select.vacuum_rooms.state == "Konyha" %} script.vacuum_kitchen
        {% elif states.input_select.vacuum_rooms.state == "Nappali" %} script.vacuum_living_room
        {% elif states.input_select.vacuum_rooms.state == "WC" %} script.vacuum_wc
        {% elif states.input_select.vacuum_rooms.state == "Fürdő" %} script.vacuum_bath
        {% elif states.input_select.vacuum_rooms.state == "Réka" %} script.vacuum_reka
        {% elif states.input_select.vacuum_rooms.state == "Zorka" %} script.vacuum_zorka
        {% elif states.input_select.vacuum_rooms.state == "Folyosó" %} script.vacuum_corridor
        {%endif %} '
  mode: single
- id: '1672958280726'
  alias: 'Reset Vacuum: Turn off Mop and Turn to Max'
  description: ''
  trigger: []
  action:
  - service: script.roborock_set_manual_mode
    target:
      entity_id: vacuum.roborock_vacuum_a15
    data:
      vacuum: max
      mopping: 'off'
    enabled: false
  - service: script.set_mopping_route
    target:
      entity_id: vacuum.roborock_vacuum_a15
    data:
      route: standard
    enabled: false
