- id: '1585261841669'
  alias: duna waterlevel notify
  description: Duna vízállás riasztás
  trigger:
  - below: '138'
    entity_id: sensor.god_duna_vizallas
    platform: numeric_state
  condition:
  - condition: template
    value_template: '{{ (as_timestamp(now()) - as_timestamp(states.automation.duna_waterlevel_notify.last_triggered  |
      default(0)) | int > 86400)}}'
  action:
  - data:
      message: A homokszigetre át lehet menni!
    service: notify.mobile_app_mi_9_se
- id: '1585672692839'
  alias: notification on tv
  description: ''
  trigger:
  - at: '18:00'
    platform: time
  condition: []
  action:
  - data:
      message: Boldi, moss fogat, kérlek!
    service: notify.nappali_tv
  mode: single
- id: '1585827520468'
  alias: Szürke víz kikapcs
  description: ''
  trigger:
  - entity_id: switch.valami
    for: 00:25:00
    from: 'off'
    platform: state
    to: 'on'
    enabled: false
  - platform: state
    entity_id:
    - switch.valami
    for:
      hours: 0
      minutes: 25
      seconds: 0
    from: 'off'
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: switch.valami
    service: switch.turn_off
  - device_id: b054553f3d464229b377f92abc7941ad
    domain: mobile_app
    type: notify
    message: Valami lekapcsolt
    title: HAssio
  mode: single
- alias: UPS changed state
  trigger:
  - platform: event
    event_type: nut.ups_event
  action:
  - service: notify.mobile_app_mi_9_se
    data_template:
      title: UPS changed state
      message: '{{ trigger.event.data.notify_msg }}'
      data:
        push:
          sound:
            name: default
            critical: 1
            volume: 1.0
  id: 8c8837088f3c4eeaa9c914db5d5d1102
- id: '1627032686499'
  alias: duna waterlevel notify szodi patak
  description: Duna vízállás Sződ-Rákosi patak
  trigger:
  - entity_id: sensor.god_duna_vizallas
    platform: numeric_state
    below: '460'
    above: '400'
  condition:
  - condition: template
    value_template: '{{ (as_timestamp(now()) - as_timestamp(states.automation.duna_waterlevel_notify_szodi_patak.last_triggered  |
      default(0)) | int > 86400)}}'
  action:
  - data:
      message: A Sződi patakra fel lehet menni!
    service: notify.mobile_app_mi_9_se
  mode: single
- id: '1630009559453'
  alias: New Automation
  description: ''
  trigger:
  - platform: state
    entity_id: switch.camera1_motion_detection
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: notify.mobile_app_mi_9_se
    data:
      message: mozgás
  mode: single
- id: '1641502924659'
  alias: Szürke víz
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: '1'
    enabled: false
  - platform: sun
    event: sunset
    offset: '5'
  condition:
  - condition: numeric_state
    entity_id: weather.otthon
    attribute: temperature
    above: '4'
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.valami
    data: {}
  mode: single
