

esphome:
  name: kazan
  platform: ESP8266
  board: nodemcuv2
  includes:
    - scheduler.h
  on_boot:
    # Alap állapot 
    then:
      
      - if:
          condition:
            # Radiátor bekapcsolva
            binary_sensor.is_on: thermo_sensor_1
          then:
            - script.execute: radiator_on
            
      - if:
          condition:
            # Padló bekapcsolva
            binary_sensor.is_on: thermo_sensor_2
          then:
            - script.execute: padlo_on
              
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Kazan Fallback Hotspot"
    password: !secret kazan_fallback

captive_portal:

# Enable logging
logger:
  #level: VERY_VERBOSE

# Enable Home Assistant API
api:
  #password: !secret nodemcu2_ota
  encryption: 
    key: !secret kazan_api

ota:
  password: !secret kazan_ota


# ============================================================================= #
# Globális változók
# ============================================================================= #
globals:
  # Time remaining
  - id: 'remaining_time'
    type: int
    restore_value: no
    initial_value: "300"

  # Store previous values to verify change.
  - id: 'remaining_time_prev'
    type: int
    restore_value: no
    initial_value: "0"


# ============================================================================= #
# i2c config
# ============================================================================= #
i2c:
  sda: D2
  scl: D1
  scan: true
  id: 'bus_a'

# I/O expander
pcf8574:
  - id: 'pcf8574_hub'
    address: 0x20
    pcf8575: false

# ============================================================================= #
# Time based automations.
# ============================================================================= #
time:
  - platform: sntp
    id: 'esphome_time'
    on_time:
      - seconds: 0
        minutes: /1
        then:
          - lambda: |-
              if (scheduled_runtime(id(pump_next).state.c_str())) {
                id(hotwater_pump).turn_on();
              }
    

# ============================================================================= #
# Bemenetek
# ============================================================================= #
binary_sensor:
  # --------------------------------------------------------------------------- #
  - id: 'thermo_sensor_1'
    name: "Kazán Radiátor"
    platform: gpio
    pin:
      pcf8574: pcf8574_hub
      number: 6
      mode:
        input: true
      inverted: true
    filters:
      - delayed_on_off: 1250ms

    on_press:
      then:
        - switch.turn_on: vs_radiator

    on_release:
      then:
        - switch.turn_off: vs_radiator



  # --------------------------------------------------------------------------- #  
  - id: 'thermo_sensor_2'
    name: "Kazán Padló"
    platform: gpio
    pin:
      pcf8574: pcf8574_hub
      number: 7
      mode:
        input: true
      inverted: true
    filters:
      - delayed_on_off: 1250ms

    on_press:
      then:
        - switch.turn_on: vs_floor

    on_release:
      then:
        - switch.turn_off: vs_floor
      


# ============================================================================= #
# Kimenetek
# ============================================================================= #
switch:

  # --------------------------------------------------------------------------- #  
  # Virtual Zone Switches which toggle the relay, and store the current state.
  - platform: template
    name: "Kazán Melegvíz keringető"
    id: 'hotwater_pump'
    lambda: return id(sw_pump_4).state;
    optimistic: true
    turn_on_action:
      # Turn on if not disabled.
      if:
        condition:
          lambda: return id(pump_duration) > 0;
        then:
          - switch.turn_on: sw_pump_4
    turn_off_action:
      - switch.turn_off: sw_pump_4
      

  # --------------------------------------------------------------------------- #  
  # Virtual Switches which toggle the relays, and store the current state.
  # Két keringető és a kazán
  - platform: template
    name: "Kazán Padlófűtés"
    id: 'vs_floor'
    lambda: |-
      return {};
    optimistic: true
    turn_on_action:
      - switch.turn_on: sw_pump_1
      - switch.turn_on: sw_pump_2
      - switch.turn_on: sw_heater
    turn_off_action:
      - switch.turn_off: sw_pump_1
      - switch.turn_off: sw_pump_2
      - if:
          condition:
            # Radiátor nincs bekapcsolva
            switch.is_off: vs_radiator
          then:
            - switch.turn_off: sw_heater


  # --------------------------------------------------------------------------- #  
  # Virtual Switches which toggle the relays, and store the current state.
  # Keringető és a kazán
  - platform: template
    name: "Kazán Radiátor"
    id: 'vs_radiator'
    lambda: |- 
      return {};
    optimistic: true
    turn_on_action:
      - switch.turn_on: sw_pump_3
      - switch.turn_on: sw_heater
    turn_off_action:
      - switch.turn_off: sw_pump_3
      - if:
          condition:
            # Padlófűtés nincs bekapcsolva
            switch.is_off: vs_floor
          then:
            - switch.turn_off: sw_heater


  # --------------------------------------------------------------------------- #
  - platform: gpio
    id: 'sw_heater'
    name: "Kazán - Fűtés SR#0"
    pin:
      pcf8574: pcf8574_hub
      number: 0
      mode:
        output: True
      inverted: True
    internal: True


  # --------------------------------------------------------------------------- #
  - platform: gpio
    id: 'sw_pump_1'
    name: "Padló Szivattyú 1 SR#1"
    pin:
      pcf8574: pcf8574_hub
      number: 1
      mode:
        output: True
      inverted: True
    internal: True


  # --------------------------------------------------------------------------- #
  - platform: gpio
    name: "Padló Szivattyú 2 SR#2"
    id: 'sw_pump_2'
    pin:
      pcf8574: pcf8574_hub
      number: 2
      mode:
        output: True
      inverted: True
    internal: True


  # --------------------------------------------------------------------------- #
  - platform: gpio
    name: "Radiátor Szivattyú SR#3"
    id: 'sw_pump_3'
    pin:
      pcf8574: pcf8574_hub
      number: 3
      mode:
        output: True
      inverted: True
    internal: True


  # --------------------------------------------------------------------------- #
  - platform: gpio
    name: "Keringető SR#4"
    id: 'sw_pump_4'
    pin:
      pcf8574: pcf8574_hub
      number: 4
      mode:
        output: True
      inverted: True
    internal: True

    on_turn_on:
      then:
        # Start the countdown timer.
        - globals.set:
            id: remaining_time
            value: !lambda return id(pump_duration).state * 60;

        # Show the remaining time.
        - sensor.template.publish:
            id: pump_remaining
            state: !lambda return id(pump_duration).state;

        # Show the "Next Time" as "now".
        - text_sensor.template.publish:
            id: pump_next
            state: "Most"

    on_turn_off:
      then:
        - sensor.template.publish:
            id: pump_remaining
            state: "0"

        # Update the next scheduled run time.
        - text_sensor.template.publish:
            id: pump_next
            state: !lambda |-
              return update_next_runtime(id(pump_times).state);

  # --------------------------------------------------------------------------- #
  - platform: gpio
    name: "Kazán - Melegvíz SR#5"
    id: 'sw_water_heater'
    pin:
      pcf8574: pcf8574_hub
      number: 5
      mode:
        output: True
      inverted: True
    internal: True   


sensor:
  # Countdown sensors.
  - platform: template
    name: "Kazán Hátralévő Keringetési Idő"
    id: 'pump_remaining'
    lambda: "return 0;"
    accuracy_decimals: 0
    unit_of_measurement: minutes
    icon: mdi:timer
    on_value:
      then:
        - if:
            condition:
              lambda: return id(remaining_time) == 0;
            then:
              - switch.turn_off: sw_pump_4   

  # Retrieve durations settings from the Home Assistant UI.
  - platform: homeassistant
    id: 'ui_pump_duration'
    entity_id: input_number.pump_duration
    on_value:
      then:
      - sensor.template.publish:
          id: pump_duration
          state: !lambda return id(ui_pump_duration).state;

  # Store durations.
  - platform: template
    name: "Kazán Keringetési Idő"
    id: 'pump_duration'


text_sensor:
  # Retrieve list of times from the Home Assistant UI.
  - platform: homeassistant
    id: 'ui_pump_times'
    entity_id: input_text.pump_times
    on_value:
      then:
        - text_sensor.template.publish:
            id: pump_times
            state: !lambda return id(ui_pump_times).state;

  # Store time lists.
  - platform: template
    name: "Kazán Keringetési Időpontok"
    id: 'pump_times'
    on_value:
      then:
        # Update the next scheduled run time.
        - text_sensor.template.publish:
            id: pump_next
            state: !lambda |-
              return update_next_runtime(id(pump_times).state);

  # Set the next scheduled time.
  - platform: template
    name: "Kazán Következő Keringetési Időpont"
    id: 'pump_next'


# Update the countdown timers every 5 seconds.
interval:
  - interval: 5s
    then:
      - lambda: |-
          if (id(remaining_time) > 0) {
            // Store the previous time.
            id(remaining_time_prev) = id(remaining_time);

            // When the relay is on.
            if (id(sw_pump_4).state) {
              // Decrement the timer.
              id(remaining_time) -= 5;

              // Turn off the relay when the time reaches zero.
              if ((id(remaining_time)) <= 0) {
                id(sw_pump_4).turn_off();
                id(remaining_time) = 0;
              }
            }

            // Update the remaining time display.
            if (id(remaining_time_prev) != id(remaining_time)) {
              //irrigation_zone1_remaining
              id(pump_remaining).publish_state( (id(remaining_time)/60) + 1 );
            }
          }

      
# Scripts
script:
  - id: 'radiator_on'
    then:
      - switch.turn_on: sw_pump_3
      - switch.turn_on: sw_heater
      
  - id: 'radiator_off'
    then:
      - switch.turn_off: sw_pump_3
      - if:
          condition:
            # Padló nincs bekapcsolva
            binary_sensor.is_off: thermo_sensor_2
          then:
            - switch.turn_off: sw_heater
      
  - id: 'padlo_on'
    then:
      - switch.turn_on: sw_pump_1
      - switch.turn_on: sw_pump_2
      - switch.turn_on: sw_heater
      
  - id: 'padlo_off'
    then:
      - switch.turn_off: sw_pump_1
      - switch.turn_off: sw_pump_2
      - if:
          condition:
            # Radiátor nincs bekapcsolva
            binary_sensor.is_off: thermo_sensor_1
          then:
            - switch.turn_off: sw_heater
